import { Inter } from "next/font/google";
import "./globals.css";
import SecondaryBar from "@/components/shared/SecondaryBar";
import Footer from "@/components/shared/Footer";
import NavigationBar from "@/components/shared/NavigationBar";
import MessageLinks from "@/components/MessageLinks";
import Socials from '@/components/Socials';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Professional Skill Development Center | Canadian University of Bangladesh",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${inter.className}`}>
        <div data-theme="mytheme">
          <SecondaryBar></SecondaryBar>
          <NavigationBar></NavigationBar>
            {children}
          <Footer></Footer>
          <MessageLinks />
          <Socials/>
          {/* need to fix socials */}
        </div>
      </body>
    </html>
  );
}
